### ISSUE TITLE
请问jniAbsolutePath应该填什么？

### ISSUE THREAD

**Issue by yxfff** [memleakpl/krbadmin#1]
Hi~
请教一个问题
Kadm5 kadm = new Kadm5(jniAbsolutePath,principal,keytab);
创建Kadm5对象时，传入的jniAbsolutePath应该如何填呢？

**Comment by maxmati** [comment]
Hi, sorry but I'll response in English.
jniAbsolutePath is path to jni library. It's libkadm5_jni-x.y.z.so (where x.y.z is version code) file which should be generated while compiling this project.

**Comment by yxfff** [comment]
Thank you for your enthusiastic answer，Now there is another problem, when I compile the project when there are some errors.Because I am not very familiar with the c language, after repeated attempts can not be resolved, if you can give some advice I would be very grateful.The following is the error message.
![s22minz wk aqr ad 8yrp](https://cloud.githubusercontent.com/assets/16175822/25517431/fb9dc772-2c21-11e7-8b7b-c4aaa3ab62ea.png)

gradle.property
jvmIncludePath=/opt/jdk1.8.0_101/include
jvmPlatformIncludePath=/opt/jdk1.8.0_101/include/linux
~

**Comment by maxmati** [comment]
It's looks like problem with your mit-krb library version. Can you provide it's version?
I'll also mention @marcmos since he is more involved into this project.

**Comment by yxfff** [comment]
Did you mean krb5-libs.x86_64
![1](https://cloud.githubusercontent.com/assets/16175822/25613097/97eb8138-2f5f-11e7-974c-36b924e202a5.png)


The first time I gradle build project,noticing me that 
/usr/include/kadm5/admin.h:48:28: error: com_err.h: No such file or directory 
I found com_err.h is at /usr/include/et/com_err.h 
So I changed admin.h to #include        <et/com_err.h>.The error has gone.
Maybe my krb-lib version is too low?

**Comment by maxmati** [comment]
It's looks like the KADM5_API_VERSION_4 define has showed up in version 1.11 (https://github.com/krb5/krb5/blob/krb5-1.11-final/src/lib/kadm5/admin.h) but I'll recommend using at least version 1.12.1 since this is one I'm using and it's working.

**Comment by yxfff** [comment]
Thank you very much for your suggestion, I have used CentOS 7 compiling the ibkadm5_jni-0.0.4.so file successfully . But my other programs are running in the environment CentOS 6.5. The krb version is 1.10.3. What should I modify if I want to use this program on CentOS 6.5?

**Comment by marcmos** [comment]
Try to change protocol to version 3 (by replacing `KADM5_API_VERSION_4` to `KADM5_API_VERSION_3`). We use rather standard protocol features in this library (principal creation/deletion, password modification) so possible compilation errors should be rather straightforward to fix.

**Comment by yxfff** [comment]
Thank you very much for  the timely reply in these days, I am very touched. After many attempts, I have successfully resolved my current problems, Thanks again.
